### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by Rishi-Mishra0704**
## Basic structure for leaderboard

- Add a basic structure for leaderboard
- Add functionality for add and refresh button
- Add scores dynamically to the page
- Use es6 arrow functions

### CODE REVIEW

**Comment by Rishi-Mishra0704** [comment]
I have removed the dist folder as it was giving linter error . 

Please run **_npm start_** for deploying the project as running **_npm run build_** will clash with the linters

**Review by osamaashraf6 — CHANGES_REQUESTED** [review]
Hi @Rishi-Mishra0704 👋, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

you-are-near

## Highlights ✔️


- [x] No linter errors. 💯
- [x] Good usage in correcting Git flow
- [x] Good adding the basic structural design.




## Required Changes ♻️
### I  Write the comment of change here because I can not leave an inline comment here😊, so 

- You did a great job 😃 at setting up the webpack with the project, but I see that no ```dist``` folder in the root directory and that's from the requirements, so please 😊try to add this folder to your root directory to stick to the requirements 🚀

| The root directory basics | 
| --- |
|    image  | 


## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rishi-Mishra0704** [comment]
Hey , like I said when I use dist directory it gives me lighthouse error as it takes a lot of time to load. So can you tell me a fix please

**Comment by Rishi-Mishra0704** [comment]
> Hi @Rishi-Mishra0704 👋,
> 
> Good job so far! 👏🥳 You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there!
> 
> you-are-near [ you-are-near ](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966) [ ](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966)
> 
> ## Highlights ✔️
> * [x]  No linter errors. 💯
> * [x]  Good usage in correcting Git flow
> * [x]  Good adding the basic structural design.
> 
> ## Required Changes ♻️
> ### I Write the comment of change here because I can not leave an inline comment here😊, so
> * You did a great job 😃 at setting up the webpack with the project, but I see that no `dist` folder in the root directory and that's from the requirements, so please 😊try to add this folder to your root directory to stick to the requirements 🚀
> 
> The root directory basics
> image
> ## Optional suggestions
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hey , like I said when I use dist directory it gives me lighthouse error as it takes a lot of time to load. So can you tell me a fix please

**Comment by Rishi-Mishra0704** [comment]
Hey , like I said when I use dist directory it gives me lighthouse error as it takes a lot of time to load. So can you tell me a fix please

**Comment by Rishi-Mishra0704** [comment]
@osamaashraf6 Please tell me how to avoid the lighthouse error with dist folder

**Review by GzimAsani — APPROVED** [review]
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- NA
### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
